CREATE TABLE ACCOUNT(
  ID VARCHAR(36) PRIMARY KEY,
  NAME VARCHAR(255) UNIQUE NOT NULL,
  CREATED_ON TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(255),
  PARENT_ACCOUNT_ID VARCHAR(36),
  FOREIGN KEY(PARENT_ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);