CREATE TABLE ACCOUNT(
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PARENT_ACCOUNT_ID VARCHAR(36),
  CREATED_ON TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(255),
  CONSTRAINT ACCOUNT__ID__PK PRIMARY KEY (ID),
  CONSTRAINT ACCOUNT__NAME__PARENT_ACCOUNT_ID__UK UNIQUE (NAME, PARENT_ACCOUNT_ID),
  CONSTRAINT ACCOUNT__PARENT_ACCOUNT_ID__FK FOREIGN KEY (PARENT_ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);