CREATE TABLE ACCOUNT(
  ID CHAR(36) PRIMARY KEY,
  NAME VARCHAR(255) UNIQUE NOT NULL,
  CREATED_ON DATETIME NOT NULL,
  DESCRIPTION VARCHAR(255),
  PARENT_ACCOUNT_ID CHAR(36),
  FOREIGN KEY(PARENT_ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);