CREATE TABLE POSTING_ENTRY(
  POSTING_ID CHAR(36) NOT NULL,
  ACCOUNT_ID VARCHAR(36) NOT NULL,
  AMOUNT DECIMAL(19, 4) NOT NULL,
  FOREIGN KEY(POSTING_ID) REFERENCES POSTING(ID),
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  PRIMARY KEY(POSTING_ID, ACCOUNT_ID)
);