CREATE TABLE ACCOUNT_CLOSURE(
  ANCESTOR_ACCOUNT_ID VARCHAR(36) NOT NULL,
  DESCENDANT_ACCOUNT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(ANCESTOR_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  FOREIGN KEY(DESCENDANT_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  PRIMARY KEY(ANCESTOR_ACCOUNT_ID, DESCENDANT_ACCOUNT_ID)
);