CREATE TABLE ACCOUNT_CLOSURE(
  ANCESTOR_ACCOUNT_ID VARCHAR(36) NOT NULL,
  DESCENDANT_ACCOUNT_ID VARCHAR(36) NOT NULL,
  CONSTRAINT ACCOUNT_CLOSURE__ANCESTOR_ACCOUNT_ID__FK FOREIGN KEY(ANCESTOR_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  CONSTRAINT ACCOUNT_CLOSURE__DESCENDANT_ACCOUNT_ID__FK FOREIGN KEY(DESCENDANT_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  CONSTRAINT ACCOUNT_CLOSURE__ANCESTOR_ACCOUNT_ID__DESCENDANT_ACCOUNT_ID__FK PRIMARY KEY(ANCESTOR_ACCOUNT_ID, DESCENDANT_ACCOUNT_ID)
);